climate_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      # Use DUCKDB_PATH env var, default to ../data/warehouse/climate.duckdb
      path: "{{ env_var('DUCKDB_PATH', '../data/warehouse/climate.duckdb') }}"
      schema: main
      threads: 4