version: 2

models:
  - name: silver_daily_weather_features
    description: >
      Cleaned daily weather table with standardized units
      and derived features for modeling.

    columns:
      - name: city_id
        tests:
          - not_null

      - name: date
        tests:
          - not_null

      - name: tmax_c
        description: "Daily maximum temperature (°C)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: -60
                max_value: 60

      - name: tmin_c
        description: "Daily minimum temperature (°C)"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: -60
                max_value: 60

      - name: tmean_c
        description: "Daily mean temperature (°C)"

      - name: precip_mm
        description: "Daily precipitation (mm)"
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 500


  - name: silver_monthly_climate
    description: >
      Monthly aggregation of daily weather by city.
      Each row is one city–month–year combination.

    columns:
      - name: city_id
        tests:
          - not_null

      - name: city_name
        tests:
          - not_null

      - name: year
        tests:
          - not_null

      - name: month
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1,2,3,4,5,6,7,8,9,10,11,12]

      - name: avg_tmean_c
        description: "Average monthly mean temperature (°C)"

      - name: avg_tmax_c
        description: "Average monthly max temperature (°C)"

      - name: avg_tmin_c
        description: "Average monthly min temperature (°C)"

      - name: total_precip_mm
        description: "Total monthly precipitation (mm)"